### PR TITLE
fix: add types for splat params

### PR DESCRIPTION
**Pull request by d0whc3r**
Following the example, `router.ts` file will be like this:

```typescript
export type Path =
  | `/`
  | `/about`
  | `/posts`
  | `/posts/:id`
  | `/posts/:id/:pid?`
  | `/posts/:id/deep`
  | `/splat/${string}`

export type Params = {
  '/posts/:id': { id: string }
  '/posts/:id/:pid?': { id: string; pid?: string }
  '/posts/:id/deep': { id: string }
  '/splat/*': { '*': string }
}
```

adding `'/splat/*': { '*': string }` because "useParams" in a splat file will return an object with one key

```typescript
export default function SplatAll() {
  const path = useParams('/splat/*')
  return <h1>All - {JSON.stringify(path)}</h1>
}
```

http://.../splat/asdf/a/d/b/e
```
path === { "*" : "asdf/a/d/b/e" }
```

### CODE REVIEW

**Comment by oedotme** [comment]
Hey @d0whc3r, thanks for submitting this PR.

I tested it out and found an issue — if there's a splat with another param it causes type key duplication. 

```ts
export type Path =
  | `/`
  | `/about`
  | `/posts`
  | `/posts/:id`
  | `/posts/:id/:pid?`
  | `/posts/:id/deep/*` // ←

export type Params = {
  '/posts/:id': { id: string }
  '/posts/:id/:pid?': { id: string; pid?: string }
  '/posts/:id/deep': { id: string }
}
```

**Comment by oedotme** [comment]
Hey @d0whc3r, thanks for submitting the PR.

I tested it out and found an issue — if there's a splat with another param it causes type keys duplication:

```ts
export type Path =
  | `/`
  | `/about`
  | `/posts`
  | `/posts/:id`
  | `/posts/:id/:pid?`
  | `/posts/:id/deep/*` // ←

export type Params = {
  '/posts/:id': { id: string }
  '/posts/:id/:pid?': { id: string; pid?: string }
  '/posts/:id/deep': { id: string } // ←
  '/posts/:id/deep': { '*': string } // ←
}
```

Mostly we'd need to add both params and splats to the same key in the previous condition:

```ts
if (param.length) {
  params.push(`'/${path}': { ${param.map((p) => p.replace(/:(.+)(\?)?/, '$1$2:') + ' string').join('; ')} }`)
}
```

Please let me know if you'd like to give it a try.

Thanks!

**Comment by d0whc3r** [comment]
@oedotme fixed 😄

**Comment by oedotme** [comment]
Hey @d0whc3r, I've pushed a small change to improve readability and to remove unnecessary splat condition. In addition, the `Path` type needed to be updated as well — as each `Params` key should match a `Path`. 

Thanks again, I'll be releasing this shortly.

**Comment by oedotme** [comment]
Released in [v1.16.0](https://github.com/oedotme/generouted/releases/tag/v1.16.0)

**Pull request merged**
